# Model Configuration
model_type: "roberta"
random_seed: 42

# Data Paths
train_path: "data/nasa_train_sample.csv"
test_path: "data/nasa_test_sample.csv"
add_train: "data/nlbse_23_train.csv"

# Output Configuration
output_path: "output"

# Prediction Mode
just_predict: false

# Label Configuration
label_to_int:
  bug: 0
  non-bug: 1

# Additional Data Handling
merge_train: false
add_labels: 
  - "bug"

# Label Mapping
map_labels: true
label_mapping:
  bug: bug
  documentation: non-bug
  feature: non-bug
  question: non-bug

# Weights & Biases Configuration
wandb:
  project: "cFS-bug-nobug"
  entity: "collab-uniba"
  log_model: false
  mode: "offline"

# Output csv with ground truth and predictions
save_predictions: false
save_predictions_path: "output/predictions.csv"